name: Auto-Update PUBG Rotation

on:
  schedule:
    - cron: "0 9 * * *"  # Every day at 9 AM UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-rotation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python pubg_map_rotation_updater.py

      - name: Commit updated index.html
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "🔁 Auto-update map rotation - $(date)"
          git push
