name: Auto Update Map Rotation

on:
  schedule:
    - cron: '0 6 * * 3'  # Wednesday at 6:00 AM UTC
    - cron: '0 6 * * 4'  # Thursday at 6:00 AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run updater script
        run: python pubg_map_rotation_updater.py

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
          git add index.html
          git commit -m "Auto-update PUBG map rotation" || echo "No changes to commit"
          git push
