name: Daily Discord Rotation Post

on:
  schedule:
    - cron: '0 9 * * *'   # 5 AM EST
    - cron: '0 15 * * *'  # 11 AM EST
    - cron: '0 21 * * *'  # 5 PM EST
    - cron: '0 3 * * *'   # 11 PM EST
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run the Discord rotation script
        run: |
          python discord_rotation_poster.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
